version: '3.8'

services:
  db:
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nginx

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"  # Открываем порт для внешних подключений
    volumes:
      - ./nginx.conf:/etc/nginx.conf  # Подключаем конфигурацию Nginx

volumes:
  db_data: