version: '3.8'

services:
  db:
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:8432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8084:8084"
    depends_on:
      - db
    networks:
      - my_network


networks:
  my_network:
      driver: bridge

volumes:
  db_data: